version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Running tests
      - npm test
    
artifacts:
  files:
    - imagedefinitions.json
